### ISSUE TITLE
Domoticz Procentage

### ISSUE THREAD

**Issue by SGiovannis** [gryzli133/RollerShutterSplit#4]
My set up is arduino mega < - Serial USB -> Raspberry PI 3+ (Domoticz). Configuration works fine UP,STOP,DOWN, but Blinds Procentage not change value. When I checked all values send to raspberry pi from arduino looks like everythink is OK. What I must install or config Domoticz to see procentage blinds/RollerShutter? I think the problem is type S_COVER for Domoticz. How can I setting this type (S_COVER) in Domoticz?

**Comment by gryzli133** [comment]
There is problem on Domoticz side, please check this topis:
https://github.com/domoticz/domoticz/issues/1543

Until now, the only one sugestion is to use dimmer, it works fine, but yeah, would be great to use it really as Blinds percentage ;-)
